export function getTheme(modo = 'dark', cor = 'roxo') {

  // ── PALETAS DARK ─────────────────────────────────────────────────────────
  const dark = {
    roxo: {
      bg: 'bg-[#110412]',
      sidebar: 'bg-[#1a071c]/80 backdrop-blur-md',
      card: 'bg-[#1a071c]/80',
      cardHover: 'hover:bg-[#e733ea]/10',
      cardActive: 'bg-[#e733ea]/20 border-l-2 border-l-[#e733ea]',
      input: 'bg-[#1a071c]/70 border-white/10 text-white placeholder-[#e733ea]/40',
      tabBg: 'bg-[#1a071c]/50',
      tabActive: 'bg-[#e733ea]/30 text-white shadow-sm',
      msgIA: 'bg-[#e733ea]/15 text-[#fce3fd] border border-[#e733ea]/30',
      msgAtd: 'bg-[#e733ea] text-white',
      btnPrimary: 'bg-[#e733ea] hover:bg-[#c92bd0] text-white', 
      avatar: 'bg-[#c92bd0] text-white',
      checkAccent: 'accent-[#e733ea]',
      accentText: 'text-[#e733ea]',
      accentBorder: 'border-[#e733ea]',
      ring: 'focus:ring-[#e733ea]',
    },
    rosa: {
      bg: 'bg-[#1a0a12]',
      sidebar: 'bg-[#1f0d17]/80 backdrop-blur-md',
      card: 'bg-[#1f0d17]/80',
      cardHover: 'hover:bg-pink-950/50',
      cardActive: 'bg-pink-900/30 border-l-2 border-l-pink-400',
      input: 'bg-[#1f0d17]/70 border-white/10 text-white placeholder-pink-900',
      tabBg: 'bg-[#1f0d17]/50',
      tabActive: 'bg-pink-950 text-white shadow-sm',
      msgIA: 'bg-pink-950/60 text-pink-100 border border-pink-900/50',
      msgAtd: 'bg-pink-600 text-white',
      btnPrimary: 'bg-pink-600 hover:bg-pink-500 text-white',
      avatar: 'bg-pink-700 text-pink-100',
      checkAccent: 'accent-pink-500',
      accentText: 'text-pink-400',
      accentBorder: 'border-pink-400',
      ring: 'focus:ring-pink-500',
    },
    verde: {
      bg: 'bg-[#061410]',
      sidebar: 'bg-[#081a14]/80 backdrop-blur-md',
      card: 'bg-[#081a14]/80',
      cardHover: 'hover:bg-emerald-950/50',
      cardActive: 'bg-emerald-900/30 border-l-2 border-l-emerald-400',
      input: 'bg-[#081a14]/70 border-white/10 text-white placeholder-emerald-900',
      tabBg: 'bg-[#081a14]/50',
      tabActive: 'bg-emerald-950 text-white shadow-sm',
      msgIA: 'bg-emerald-950/60 text-emerald-100 border border-emerald-900/50',
      msgAtd: 'bg-emerald-600 text-white',
      btnPrimary: 'bg-emerald-600 hover:bg-emerald-500 text-white',
      avatar: 'bg-emerald-700 text-emerald-100',
      checkAccent: 'accent-emerald-500',
      accentText: 'text-emerald-400',
      accentBorder: 'border-emerald-400',
      ring: 'focus:ring-emerald-500',
    },
    amarelo: {
      bg: 'bg-[#141008]',
      sidebar: 'bg-[#1a140a]/80 backdrop-blur-md',
      card: 'bg-[#1a140a]/80',
      cardHover: 'hover:bg-amber-950/50',
      cardActive: 'bg-amber-900/30 border-l-2 border-l-amber-400',
      input: 'bg-[#1a140a]/70 border-white/10 text-white placeholder-amber-900',
      tabBg: 'bg-[#1a140a]/50',
      tabActive: 'bg-amber-950 text-white shadow-sm',
      msgIA: 'bg-amber-950/60 text-amber-100 border border-amber-900/50',
      msgAtd: 'bg-amber-500 text-white',
      btnPrimary: 'bg-amber-500 hover:bg-amber-400 text-white',
      avatar: 'bg-amber-600 text-amber-100',
      checkAccent: 'accent-amber-500',
      accentText: 'text-amber-400',
      accentBorder: 'border-amber-400',
      ring: 'focus:ring-amber-500',
    },
    azul: {
      bg: 'bg-[#050e1a]',
      sidebar: 'bg-[#071220]/80 backdrop-blur-md',
      card: 'bg-[#071220]/80',
      cardHover: 'hover:bg-sky-950/50',
      cardActive: 'bg-sky-900/30 border-l-2 border-l-sky-400',
      input: 'bg-[#071220]/70 border-white/10 text-white placeholder-sky-900',
      tabBg: 'bg-[#071220]/50',
      tabActive: 'bg-sky-950 text-white shadow-sm',
      msgIA: 'bg-sky-950/60 text-sky-100 border border-sky-900/50',
      msgAtd: 'bg-sky-500 text-white',
      btnPrimary: 'bg-sky-500 hover:bg-sky-400 text-white',
      avatar: 'bg-sky-600 text-sky-100',
      checkAccent: 'accent-sky-500',
      accentText: 'text-sky-400',
      accentBorder: 'border-sky-400',
      ring: 'focus:ring-sky-500',
    },
    vermelho: {
      bg: 'bg-[#140808]',
      sidebar: 'bg-[#1a0a0a]/80 backdrop-blur-md',
      card: 'bg-[#1a0a0a]/80',
      cardHover: 'hover:bg-rose-950/50',
      cardActive: 'bg-rose-900/30 border-l-2 border-l-rose-400',
      input: 'bg-[#1a0a0a]/70 border-white/10 text-white placeholder-rose-900',
      tabBg: 'bg-[#1a0a0a]/50',
      tabActive: 'bg-rose-950 text-white shadow-sm',
      msgIA: 'bg-rose-950/60 text-rose-100 border border-rose-900/50',
      msgAtd: 'bg-rose-600 text-white',
      btnPrimary: 'bg-rose-600 hover:bg-rose-500 text-white',
      avatar: 'bg-rose-700 text-rose-100',
      checkAccent: 'accent-rose-500',
      accentText: 'text-rose-400',
      accentBorder: 'border-rose-400',
      ring: 'focus:ring-rose-500',
    },
    neutro: {
      bg: 'bg-[#0a0a0a]',
      sidebar: 'bg-[#111111]/80 backdrop-blur-md',
      card: 'bg-[#111111]/80',
      cardHover: 'hover:bg-zinc-800/50',
      cardActive: 'bg-zinc-800 border-l-2 border-l-zinc-400',
      input: 'bg-[#111111]/70 border-white/10 text-white placeholder-zinc-600',
      tabBg: 'bg-[#111111]/50',
      tabActive: 'bg-zinc-800 text-white shadow-sm',
      msgIA: 'bg-zinc-800/60 text-zinc-200 border border-zinc-700/50',
      msgAtd: 'bg-zinc-600 text-white',
      btnPrimary: 'bg-zinc-600 hover:bg-zinc-500 text-white',
      avatar: 'bg-zinc-700 text-zinc-100',
      checkAccent: 'accent-zinc-500',
      accentText: 'text-zinc-300',
      accentBorder: 'border-zinc-400',
      ring: 'focus:ring-zinc-500',
    },
  }

  // ── PALETAS LIGHT ────────────────────────────────────────────────────────
  const light = {
    roxo: {
      bg: 'bg-[#fdf8fd]', 
      sidebar: 'bg-white/80 backdrop-blur-md',
      card: 'bg-white/90',
      cardHover: 'hover:bg-[#fbf0fc]',
      cardActive: 'bg-[#e733ea]/10 border-l-2 border-l-[#e733ea]',
      input: 'bg-white border-slate-200 text-slate-900 placeholder-slate-400',
      tabBg: 'bg-slate-100/80',
      tabActive: 'bg-white text-[#b81bbd] shadow-sm', 
      msgIA: 'bg-[#e733ea]/10 text-[#731075] border border-[#e733ea]/20',
      msgAtd: 'bg-[#e733ea] text-white',
      btnPrimary: 'bg-[#e733ea] hover:bg-[#c92bd0] text-white',
      avatar: 'bg-[#e733ea] text-white',
      checkAccent: 'accent-[#e733ea]',
      accentText: 'text-[#e733ea]',
      accentBorder: 'border-[#e733ea]',
      ring: 'focus:ring-[#e733ea]',
    },
    rosa: {
      bg: 'bg-pink-50',
      sidebar: 'bg-white/80 backdrop-blur-md',
      card: 'bg-white/90',
      cardHover: 'hover:bg-pink-50',
      cardActive: 'bg-pink-50 border-l-2 border-l-pink-500',
      input: 'bg-white border-pink-200 text-slate-900 placeholder-slate-400',
      tabBg: 'bg-pink-100/60',
      tabActive: 'bg-white text-pink-700 shadow-sm',
      msgIA: 'bg-pink-50 text-pink-900 border border-pink-200',
      msgAtd: 'bg-pink-500 text-white',
      btnPrimary: 'bg-pink-600 hover:bg-pink-700 text-white',
      avatar: 'bg-pink-600 text-white',
      checkAccent: 'accent-pink-600',
      accentText: 'text-pink-600',
      accentBorder: 'border-pink-500',
      ring: 'focus:ring-pink-500',
    },
    verde: {
      bg: 'bg-emerald-50',
      sidebar: 'bg-white/80 backdrop-blur-md',
      card: 'bg-white/90',
      cardHover: 'hover:bg-emerald-50',
      cardActive: 'bg-emerald-50 border-l-2 border-l-emerald-500',
      input: 'bg-white border-emerald-200 text-slate-900 placeholder-slate-400',
      tabBg: 'bg-emerald-100/60',
      tabActive: 'bg-white text-emerald-700 shadow-sm',
      msgIA: 'bg-emerald-50 text-emerald-900 border border-emerald-200',
      msgAtd: 'bg-emerald-600 text-white',
      btnPrimary: 'bg-emerald-600 hover:bg-emerald-700 text-white',
      avatar: 'bg-emerald-600 text-white',
      checkAccent: 'accent-emerald-600',
      accentText: 'text-emerald-600',
      accentBorder: 'border-emerald-500',
      ring: 'focus:ring-emerald-500',
    },
    amarelo: {
      bg: 'bg-amber-50',
      sidebar: 'bg-white/80 backdrop-blur-md',
      card: 'bg-white/90',
      cardHover: 'hover:bg-amber-50',
      cardActive: 'bg-amber-50 border-l-2 border-l-amber-500',
      input: 'bg-white border-amber-200 text-slate-900 placeholder-slate-400',
      tabBg: 'bg-amber-100/60',
      tabActive: 'bg-white text-amber-700 shadow-sm',
      msgIA: 'bg-amber-50 text-amber-900 border border-amber-200',
      msgAtd: 'bg-amber-500 text-white',
      btnPrimary: 'bg-amber-500 hover:bg-amber-600 text-white',
      avatar: 'bg-amber-500 text-white',
      checkAccent: 'accent-amber-600',
      accentText: 'text-amber-600',
      accentBorder: 'border-amber-500',
      ring: 'focus:ring-amber-500',
    },
    azul: {
      bg: 'bg-sky-50',
      sidebar: 'bg-white/80 backdrop-blur-md',
      card: 'bg-white/90',
      cardHover: 'hover:bg-sky-50',
      cardActive: 'bg-sky-50 border-l-2 border-l-sky-500',
      input: 'bg-white border-sky-200 text-slate-900 placeholder-slate-400',
      tabBg: 'bg-sky-100/60',
      tabActive: 'bg-white text-sky-700 shadow-sm',
      msgIA: 'bg-sky-50 text-sky-900 border border-sky-200',
      msgAtd: 'bg-sky-500 text-white',
      btnPrimary: 'bg-sky-500 hover:bg-sky-600 text-white',
      avatar: 'bg-sky-500 text-white',
      checkAccent: 'accent-sky-600',
      accentText: 'text-sky-600',
      accentBorder: 'border-sky-500',
      ring: 'focus:ring-sky-500',
    },
    vermelho: {
      bg: 'bg-rose-50',
      sidebar: 'bg-white/80 backdrop-blur-md',
      card: 'bg-white/90',
      cardHover: 'hover:bg-rose-50',
      cardActive: 'bg-rose-50 border-l-2 border-l-rose-500',
      input: 'bg-white border-rose-200 text-slate-900 placeholder-slate-400',
      tabBg: 'bg-rose-100/60',
      tabActive: 'bg-white text-rose-700 shadow-sm',
      msgIA: 'bg-rose-50 text-rose-900 border border-rose-200',
      msgAtd: 'bg-rose-600 text-white',
      btnPrimary: 'bg-rose-600 hover:bg-rose-700 text-white',
      avatar: 'bg-rose-600 text-white',
      checkAccent: 'accent-rose-600',
      accentText: 'text-rose-600',
      accentBorder: 'border-rose-500',
      ring: 'focus:ring-rose-500',
    },
    neutro: {
      bg: 'bg-zinc-100',
      sidebar: 'bg-white/80 backdrop-blur-md',
      card: 'bg-white/90',
      cardHover: 'hover:bg-zinc-50',
      cardActive: 'bg-zinc-100 border-l-2 border-l-zinc-600',
      input: 'bg-white border-zinc-200 text-slate-900 placeholder-slate-400',
      tabBg: 'bg-zinc-200/60',
      tabActive: 'bg-white text-zinc-800 shadow-sm',
      msgIA: 'bg-zinc-100 text-zinc-900 border border-zinc-200',
      msgAtd: 'bg-zinc-700 text-white',
      btnPrimary: 'bg-zinc-700 hover:bg-zinc-800 text-white',
      avatar: 'bg-zinc-700 text-white',
      checkAccent: 'accent-zinc-600',
      accentText: 'text-zinc-700',
      accentBorder: 'border-zinc-600',
      ring: 'focus:ring-zinc-500',
    },
  }

  // ── PARTES COMUNS ─────────────────────────────────
  const shared_dark = {
    border: 'border-white/8',
    text: 'text-white',
    subtext: 'text-slate-300',
    muted: 'text-slate-500',
    tabInactive: 'text-slate-500 hover:text-slate-300',
    msgClient: 'bg-slate-800/80 text-slate-200 border border-white/5',
    header: 'bg-transparent border-white/8',
    topbar: 'bg-transparent border-white/8',
    modalBg: 'bg-slate-900 border-white/10',
    btnSecondary: 'bg-slate-800 hover:bg-slate-700 text-slate-300 border border-white/10',
    btnDanger: 'bg-red-900/50 hover:bg-red-800 text-red-300 border border-red-800',
  }

  const shared_light = {
    border: 'border-slate-200/80',
    text: 'text-slate-900',
    subtext: 'text-slate-600',
    muted: 'text-slate-400',
    tabInactive: 'text-slate-500 hover:text-slate-700',
    msgClient: 'bg-white text-slate-800 border border-slate-200',
    header: 'bg-transparent border-slate-200/80',
    topbar: 'bg-transparent border-slate-200/80',
    modalBg: 'bg-white border-slate-200',
    btnSecondary: 'bg-white hover:bg-slate-50 text-slate-700 border border-slate-200',
    btnDanger: 'bg-red-50 hover:bg-red-100 text-red-600 border border-red-200',
  }

  const palette = modo === 'dark'
    ? { ...(dark[cor] || dark.roxo), ...shared_dark }
    : { ...(light[cor] || light.roxo), ...shared_light }

  return palette
}